<?php

define('FLICKR_API_KEY', $_ENV['FLICKR_API_KEY']);
define('FLICKR_API_SECRET', $_ENV['FLICKR_API_SECRET']);

define('FIVEHUNDREDPX_API_KEY', $_ENV['500PX_API_KEY']);
define('FIVEHUNDREDPX_API_SECRET', $_ENV['500PX_API_SECRET']);

?>